In [1]:
import os
import numpy as np

In [2]:
data_path='dataset'

In [3]:
folders=os.listdir(data_path)
print(folders)
labels=[i for i in range(len(folders))]
print(labels)

['a', 'ae', 'e', 'u']
[0, 1, 2, 3]


In [4]:
category_dict={'a':0,'ae':1,'e':2,'u':3}
print(category_dict)

{'a': 0, 'ae': 1, 'e': 2, 'u': 3}


In [5]:
import cv2
data=[]
target=[]

for folders in folders:
    img_folder_path=os.path.join(data_path,folders)
    #print(img_folder_path)
    images=os.listdir(img_folder_path)
    for images in images:
        images_path=os.path.join(img_folder_path,images)
        img=cv2.imread(images_path,0)
        img=cv2.resize(img,(8,8))
        data.append(img)
        target.append(category_dict[folders])

    

In [6]:
print(len(data),len(target))

270 270


In [7]:
print(data[10])
print(target[10])

[[255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255]
 [  0   0 255 255   6 255   0 255]
 [255 255 255   0   0   0   0 255]
 [255 255  95 255 255   0 255  46]
 [255 255 255 255 255   0 255 255]
 [255 255 255 255 255   0 255 255]
 [255 255 255 255 255 255 255 255]]
0


In [8]:
data=np.array(data)
data=data.reshape(data.shape[0],data.shape[1]*data.shape[2])

target=np.array(target)

print(data.shape)
print(target.shape)

(270, 64)
(270,)


In [9]:
np.save('data',data)
np.save('target',target)
